// generated by PharoJS *** DO NOT EDIT *** on 2018-09-27T16:23:21.694554+02:00 by noury
var global=global||this
global.Smalltalk=global.Smalltalk||(function Smalltalk(){});
Object.defineProperty(Object.prototype,"$def",{value:
 function $def(aFunc){
	Object.defineProperty(this,aFunc.name,{writable:true,value:aFunc})}})
var require
global.Smalltalk.require=require
function PjClass(){};
Smalltalk.theClassClass=PjClass;
