Class {
	#name : #PjToolsTest1,
	#superclass : #PjApplication,
	#category : #'PharoJsTools-Tests'
}

{ #category : #'as yet unclassified' }
PjToolsTest1 class >> bridgeClientClass [
	^ nil
]

{ #category : #'as yet unclassified' }
PjToolsTest1 class >> c1 [
	^ self subclassResponsibility
]

{ #category : #'as yet unclassified' }
PjToolsTest1 >> m1 [
	^ self subclassResponsibility
]

{ #category : #'as yet unclassified' }
PjToolsTest1 >> m2 [
	^ self subclassResponsibility
]

{ #category : #'as yet unclassified' }
PjToolsTest1 >> m3 [
	^ 18
]
