Class {
	#name : #PjCompositeForSerializationTest,
	#superclass : #Object,
	#instVars : [
		'a',
		'b'
	],
	#category : #'PharoJs-Base-Serialization-Deprecated-Tests'
}

{ #category : #accessing }
PjCompositeForSerializationTest >> a [
	^ a
]

{ #category : #accessing }
PjCompositeForSerializationTest >> a: anObject [
	a := anObject
]

{ #category : #accessing }
PjCompositeForSerializationTest >> b [
	^ b
]

{ #category : #accessing }
PjCompositeForSerializationTest >> b: anObject [
	b := anObject
]
