Class {
	#name : #PhxJsonObjectForTestWithAlphabeticallyOrderedIVs,
	#superclass : #Object,
	#instVars : [
		'aaaa',
		'bbbb',
		'cccc'
	],
	#category : #'PharoJs-Base-Serialization-Tests'
}

{ #category : #accessing }
PhxJsonObjectForTestWithAlphabeticallyOrderedIVs >> aaaa [

	^ aaaa
]

{ #category : #accessing }
PhxJsonObjectForTestWithAlphabeticallyOrderedIVs >> aaaa: anObject [

	aaaa := anObject
]

{ #category : #accessing }
PhxJsonObjectForTestWithAlphabeticallyOrderedIVs >> bbbb [

	^ bbbb
]

{ #category : #accessing }
PhxJsonObjectForTestWithAlphabeticallyOrderedIVs >> bbbb: anObject [

	bbbb := anObject
]

{ #category : #accessing }
PhxJsonObjectForTestWithAlphabeticallyOrderedIVs >> cccc [

	^ cccc
]

{ #category : #accessing }
PhxJsonObjectForTestWithAlphabeticallyOrderedIVs >> cccc: anObject [

	cccc := anObject
]
