Class {
	#name : #PjClientForJavascriptInitializationTest,
	#superclass : #Object,
	#category : #'PharoJsTranspiler-Tests-Support'
}

{ #category : #initializing }
PjClientForJavascriptInitializationTest class >> initialize [

]

{ #category : #initializing }
PjClientForJavascriptInitializationTest class >> javascriptInitialize [

]

{ #category : #any }
PjClientForJavascriptInitializationTest >> m [
	PjProviderForInitializationTest new
]
